# Generated by Django 5.0.4 on 2024-04-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
